export const browserCoreExamples = [
  "kibo browser status",
  "kibo browser start",
  "kibo browser stop",
  "kibo browser tabs",
  "kibo browser open https://example.com",
  "kibo browser focus abcd1234",
  "kibo browser close abcd1234",
  "kibo browser screenshot",
  "kibo browser screenshot --full-page",
  "kibo browser screenshot --ref 12",
  "kibo browser snapshot",
  "kibo browser snapshot --format aria --limit 200",
  "kibo browser snapshot --efficient",
  "kibo browser snapshot --labels",
];

export const browserActionExamples = [
  "kibo browser navigate https://example.com",
  "kibo browser resize 1280 720",
  "kibo browser click 12 --double",
  'kibo browser type 23 "hello" --submit',
  "kibo browser press Enter",
  "kibo browser hover 44",
  "kibo browser drag 10 11",
  "kibo browser select 9 OptionA OptionB",
  "kibo browser upload /tmp/kibo/uploads/file.pdf",
  'kibo browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "kibo browser dialog --accept",
  'kibo browser wait --text "Done"',
  "kibo browser evaluate --fn '(el) => el.textContent' --ref 7",
  "kibo browser console --level error",
  "kibo browser pdf",
];
